openapi: 3.0.0
info:
  contact:
    email: contact@rektangularstudios.com
    name: Rektangular Studios
    url: https://rektangularstudios.com
  license:
    name: MIT
    url: https://raw.githubusercontent.com/RektangularStudios/novellia-sdk/main/LICENSE
  termsOfService: TODO
  title: novellia
  version: 0.8.0
servers:
- description: API Gateway
  url: api.rektangularstudios.com/novellia
paths:
  /wallet/{wallet_address}:
    get:
      description: Returns the tokens held in a wallet address
      operationId: get-wallet
      parameters:
      - description: Address of Cardano wallet to use
        explode: false
        in: path
        name: wallet_address
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                description: List of tokens held by Cardano wallet
                items:
                  $ref: '#/components/schemas/Token'
                type: array
          description: OK
        "400":
          description: Bad Request
      summary: Your GET endpoint
      tags: []
  /workflow/minter/nvla:
    get:
      description: Returns execution information such as transaction cost
      operationId: get-workflow-minter-nvla
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowInformation'
          description: OK
    post:
      description: Returns a transaction to mint NVLA and deposit it to a specified
        address
      operationId: post-workflow-minter-nvla
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MinterInfo'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardanoTransaction'
          description: OK
        "400":
          description: Bad Request
  /cardano/transaction:
    post:
      description: Submits a transaction to Cardano
      operationId: post-cardano-transaction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardanoTransaction'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /cardano/tip:
    get:
      description: Returns Cardano's latest block and epoch
      operationId: get-cardano-tip
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardanoTip'
          description: OK
      summary: Your GET endpoint
      tags: []
  /status:
    get:
      description: Information regarding status of microservice
      operationId: get-status
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
          description: OK
      summary: Your GET endpoint
      tags: []
  /products:
    get:
      description: Returns a list of product IDs
      operationId: get-products
      parameters:
      - description: Filter product results by market
        explode: true
        in: query
        name: market_id
        required: false
        schema:
          type: string
        style: form
      - description: Filter product results by organization
        explode: true
        in: query
        name: organization_id
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsList'
          description: OK
      summary: Your GET endpoint
      tags: []
    post:
      description: Returns product information for a specific list of products
      operationId: post-products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductsList'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Product'
                type: array
          description: OK
  /orders:
    get:
      description: Gets an order
      operationId: get-orders
      parameters:
      - description: Identifier for order
        explode: true
        in: query
        name: order_id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: OK
      summary: Your GET endpoint
      tags: []
    post:
      description: Creates an order
      operationId: post-orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
          application/xml:
            schema:
              properties: {}
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderCreated'
          description: OK
components:
  schemas:
    Token:
      description: Generalizes the data required to describe a token in a Cardano
        wallet.
      example:
        amount: 0
        name: name
        description: description
        asset_id: asset_id
      properties:
        asset_id:
          description: Token asset ID registered on Cardano
          type: string
        amount:
          description: Amount of token held in Cardano wallet (in discrete units,
            i.e. lovelace)
          type: integer
        name:
          description: Name or ticker as interpreted by Novellia (e.g. NVLA, ADA)
          type: string
        description:
          description: Short description of token as interpreted by Novellia
          type: string
      required:
      - amount
      - asset_id
      title: Token
      type: object
    CardanoTransaction:
      description: A Cardano transaction to be signed and submitted.
      example:
        fee_lovelace: 0
        signed: true
        transaction: transaction
      properties:
        transaction:
          description: text of transaction file
          type: string
        fee_lovelace:
          description: Cost to submit TX in lovelace (1 ADA = 1,000,000 lovelace)
          type: integer
        signed:
          description: Indicates if the transaction is signed or raw
          type: boolean
      required:
      - fee_lovelace
      - signed
      - transaction
      title: CardanoTransaction
      type: object
    MinterInfo:
      description: Generic information required for minter workflows.
      example:
        wallet_address: wallet_address
        minter_deposit_address: minter_deposit_address
      properties:
        wallet_address:
          description: Wallet that pays transaction fee
          type: string
        minter_deposit_address:
          description: Wallet that received minted tokens
          type: string
      required:
      - minter_deposit_address
      - wallet_address
      title: MinterInfo
      type: object
    WorkflowInformation:
      description: Returns preconditions relevant to a user wanting to execute a workflow.
        I.e. costs.
      example:
        fee_lovelace: 0
      properties:
        fee_lovelace:
          description: The lovelace cost to execute the workflow
          type: integer
      title: WorkflowInformation
      type: object
    CardanoTip:
      description: Cardano chain tip information
      example:
        block: 0
        epoch: 6
      properties:
        block:
          description: Latest Cardano block
          type: integer
        epoch:
          description: Latest Cardano epoch
          type: integer
      required:
      - block
      - epoch
      title: CardanoTip
      type: object
    Status:
      description: Status of microservice, indicating service availabilities
      example:
        cardano:
          initialized: true
          sync_percentage: 0.8008281904610115
        maintenance: true
        status: status
      properties:
        cardano:
          $ref: '#/components/schemas/Status_cardano'
        maintenance:
          description: kill-switch to tell users that the backend is not working correctly
            / is under maintenance
          type: boolean
        status:
          description: Status string. "UP" if everything is fine.
          type: string
      required:
      - cardano
      - maintenance
      - status
      title: Status
      type: object
    Product:
      description: Describes a Product served from the Novellia microservice
      example:
        market:
          name: name
          market_id: market_id
          description: description
        metadata:
          date_listed: date_listed
          date_available: date_available
        product:
          novellia_standard_token:
            image: image
            copyright: copyright
            extension:
            - extension
            - extension
            resource:
            - content_type: content_type
              resource_id: resource_id
              description: description
              priority: 9
              url:
              - url
              - url
              multihash: multihash
              hash_source_type: hash_source_type
            - content_type: content_type
              resource_id: resource_id
              description: description
              priority: 9
              url:
              - url
              - url
              multihash: multihash
              hash_source_type: hash_source_type
            description:
              short: short
              long: long
            version: 2
            tags:
            - tags
            - tags
            name: name
            publisher:
            - publisher
            - publisher
            native_token:
              policy_id: policy_id
              asset_id: asset_id
            commission:
            - address: address
              name: name
              percent: 3.616076749251911
            - address: address
              name: name
              percent: 3.616076749251911
            id: 7
            novellia_version: 2
          product_id: product_id
          extended_721_token:
            image: image
            extension:
            - extension
            - extension
            name: name
            native_token:
              policy_id: policy_id
              asset_id: asset_id
            id: 5
          native_token:
            policy_id: policy_id
            asset_id: asset_id
          novellia_product:
            copyright: copyright
            resource:
            - content_type: content_type
              resource_id: resource_id
              description: description
              priority: 9
              url:
              - url
              - url
              multihash: multihash
              hash_source_type: hash_source_type
            - content_type: content_type
              resource_id: resource_id
              description: description
              priority: 9
              url:
              - url
              - url
              multihash: multihash
              hash_source_type: hash_source_type
            name: name
            publisher:
            - publisher
            - publisher
            description:
              short: short
              long: long
            commission:
            - address: address
              name: name
              percent: 3.616076749251911
            - address: address
              name: name
              percent: 3.616076749251911
            id: 7
            version: 4
            tags:
            - tags
            - tags
        organization:
          organization_id: organization_id
          name: name
          description: description
        attribution:
        - author_name: author_name
          work_attributed: work_attributed
          url:
          - url
          - url
        - author_name: author_name
          work_attributed: work_attributed
          url:
          - url
          - url
        stock:
          total_supply: 5.962133916683182
          available: 1.4658129805029452
        pricing:
          max_order_size: 6
          price_unit_amount: 0.8008281904610115
          price_currency_id: price_currency_id
      properties:
        pricing:
          $ref: '#/components/schemas/Product_pricing'
        organization:
          $ref: '#/components/schemas/Product_organization'
        market:
          $ref: '#/components/schemas/Product_market'
        stock:
          $ref: '#/components/schemas/Product_stock'
        metadata:
          $ref: '#/components/schemas/Product_metadata'
        product:
          $ref: '#/components/schemas/Product_product'
        attribution:
          description: List of entities to give attribution to for product
          items:
            $ref: '#/components/schemas/Attribution'
          type: array
      required:
      - market
      - metadata
      - organization
      - pricing
      - product
      - stock
      type: object
    Order:
      description: Describes a single order
      example:
        order_status: order_status
        description: description
        payment:
          payment_address: payment_address
          payment_status: payment_status
          price_amount: 6.027456183070403
          price_currency_id: price_currency_id
        items:
        - quantity: 0
          product_id: product_id
        - quantity: 0
          product_id: product_id
        order_id: order_id
        customer:
          delivery_address: delivery_address
      properties:
        items:
          items:
            $ref: '#/components/schemas/Order_items'
          type: array
        customer:
          $ref: '#/components/schemas/Order_customer'
        payment:
          $ref: '#/components/schemas/Order_payment'
        order_id:
          description: Order ID for future reference
          type: string
        description:
          description: Description of order, useful metadata such as presale that
            occurred, etc.
          type: string
        order_status:
          description: Order status (i.e. awaiting payment, queued, refunded, ...)
          type: string
      required:
      - customer
      - description
      - items
      - order_id
      - order_status
      title: Order
      type: object
      x-examples:
        order-paid-with-ada:
          products:
          - product_id: PROD-01D78XYFJ1PRM1WPBAOU8JQMNV
            quantity: 4
          - product_id: PROD-01D78XYFJ1PRM1WPBCBT3VHMNV
            quantity: 2
          customer:
            delivery_address: addr1q80u75kavwd5sc7j52x0k8nrqd46540vcjgsvl4fhxjqqs60vcjwf9llp7rv006f0dqyffltyyyzpzl9vct4mp7wjdaspwq39a
          payment:
            payment_address: addr1q80u75kavwd5sc7j52x0k8nrqd46540vcjgsvl4fhxjqqs60vcjwf9llp7rv006f0dqyffltyyyzpzl9vct4mp7wjdaspwq39a
            price_currency_id: ada
            price_amount: 20
            status: AWAITING_PAYMENT
          order_id: ORDER-01D78XYFJ1PRM1WPBCBT3VHMNV
    OrderCreated:
      description: Response after an order is made
      example:
        order_id: order_id
      properties:
        order_id:
          type: string
      required:
      - order_id
      title: OrderCreated
      type: object
      x-examples:
        example-1:
          order_id: ORDER-01D78XYFJ1PRM1WPBCBT3VHMNV
    OccultaNovelliaCharacter:
      description: Model for an Occulta Novellia character
      properties:
        occulta_novellia_version:
          description: Specification version for parsing the resource
          type: integer
        name:
          description: Character name
          type: string
        card:
          $ref: '#/components/schemas/OccultaNovelliaCharacter_card'
        progression:
          $ref: '#/components/schemas/OccultaNovelliaCharacter_progression'
        stats:
          $ref: '#/components/schemas/OccultaNovelliaCharacter_stats'
        attributes:
          description: List of attribute strings relating to character abilities,
            faction, types, etc.
          items:
            type: string
          type: array
        description:
          description: Description of character
          type: string
      required:
      - attributes
      - card
      - description
      - name
      - occulta_novellia_version
      - progression
      - stats
      title: OccultaNovelliaCharacter
      type: object
      x-examples:
        Iscara the Ten Thousand Guns:
          occulta_novellia_version: 1
          name: Iscara the Ten Thousand Guns
          card:
            number: 2
            release_set: Presale 1
          progression:
            class: Iscara of Grevania
            stage: 1
          stats:
            health: 8
            attack: 6
            move: 1
            slots: 2
          attributes:
          - Operator's Guild
          - Human
          - Tainted
          - Rifle
          - Sure Shot
          - Operator
          - Ten Thousand Guns
          description: Rumors say the leader of the Operator's Guild is possessed
            by a demonic entity that lets her morph into monsters and spit in the
            face of death itself. The Grevans refuse to acknowledge her humanity,
            referring to her as Ten Thousand Guns. They hide their children at dawn,
            hoping that the pretty woman, usually seen in a dress, won't take them.
    OffChainResource:
      description: Off-chain resource used in Novellia Token Standard
      example:
        content_type: content_type
        resource_id: resource_id
        description: description
        priority: 9
        url:
        - url
        - url
        multihash: multihash
        hash_source_type: hash_source_type
      properties:
        resource_id:
          description: Resource identifier interpreted by application. These may correspond
            to specific names resources a client expects.
          type: string
        description:
          description: Short text describing resource. Helpful to know what the resource
            should have been if the resource breaks.
          type: string
        priority:
          description: Order to load resource. Lower numbers load first. Resources
            with the same name will progressively overwrite each other.
          type: integer
        multihash:
          description: The multihash of the resource. In most cases, this may be identical
            to an IPFS hash.
          type: string
        hash_source_type:
          description: Hint regarding file state prior to hashing (ipfs, direct)
          type: string
        url:
          description: Redundant resource URLs. These should all point to the same
            file on different hosts.
          items:
            type: string
          type: array
        content_type:
          description: MIME type of resource.
          type: string
      required:
      - content_type
      - description
      - hash_source_type
      - multihash
      - priority
      - resource_id
      - url
      title: OffChainResource
      type: object
      x-examples:
        example-1:
          resource_id: Card
          description: Low Resolution
          priority: 0
          multihash: QmSXVm14pVec78vjGgQBMygwKYvDeyKyLs4UCic7UspxEv
          hash_source_type: ipfs
          url:
          - sia://nAGazETmJJBvTnz5G50vt9gla_p6vctykk7uYy7N4cbbUQ
          - ipfs://QmSXVm14pVec78vjGgQBMygwKYvDeyKyLs4UCic7UspxEv
          - https://rektangularstudios.com/static
          content_type: image/png
    DescriptionSet:
      description: Set of descriptions
      example:
        short: short
        long: long
      properties:
        short:
          description: A short description makes a good header
          type: string
        long:
          description: A long description makes a good paragraph body. Supports Markdown.
          type: string
      required:
      - long
      - short
      title: DescriptionSet
      type: object
      x-examples:
        example-1:
          short: Occulta Novellia Character
          long: |-
            # Take back gaming!
            A character token for the surreal horror game Occulta Novellia. This token will grant access to a playable character.
    Commission:
      description: A recommended commission for clients that will abide by it
      example:
        address: address
        name: name
        percent: 3.616076749251911
      properties:
        name:
          description: Name of entity taking commissions
          type: string
        address:
          description: Address to deposit commissions
          type: string
        percent:
          description: Recommended commission percentage
          type: number
      required:
      - address
      - name
      title: Commission
      type: object
      x-examples:
        Rektangular Studios Commission:
          name: Rektangular Studios Inc.
          address: addr1q80u75kavwd5sc7j52x0k8nrqd46540vcjgsvl4fhxjqqs60vcjwf9llp7rv006f0dqyffltyyyzpzl9vct4mp7wjdaspwq39a
          percent: "0.03"
    NovelliaStandardToken:
      description: Novellia Token Standard on-chain metadata
      example:
        image: image
        copyright: copyright
        extension:
        - extension
        - extension
        resource:
        - content_type: content_type
          resource_id: resource_id
          description: description
          priority: 9
          url:
          - url
          - url
          multihash: multihash
          hash_source_type: hash_source_type
        - content_type: content_type
          resource_id: resource_id
          description: description
          priority: 9
          url:
          - url
          - url
          multihash: multihash
          hash_source_type: hash_source_type
        description:
          short: short
          long: long
        version: 2
        tags:
        - tags
        - tags
        name: name
        publisher:
        - publisher
        - publisher
        native_token:
          policy_id: policy_id
          asset_id: asset_id
        commission:
        - address: address
          name: name
          percent: 3.616076749251911
        - address: address
          name: name
          percent: 3.616076749251911
        id: 7
        novellia_version: 2
      minProperties: 0
      properties:
        copyright:
          description: Attribution of rights.
          type: string
        publisher:
          description: List of publishers or entities involved in token creation.
            Useful for onlookers to determine token origin. These can be URLs.
          items:
            type: string
          type: array
        version:
          description: Token version. May have future use such as for clients optionally
            using later metadata iterations.
          type: integer
        extension:
          description: List of extensions for parser to understand feature set. This
            may be empty, in which case the token is interpreted as just a 721 token.
          items:
            type: string
          type: array
        id:
          description: Token number in a set. Redundant field which makes no sense
            for tokens without a total-order.
          type: integer
        name:
          description: Display name for token.
          type: string
        image:
          description: Image URL without source redundancy.
          type: string
        description:
          $ref: '#/components/schemas/DescriptionSet'
        resource:
          items:
            $ref: '#/components/schemas/OffChainResource'
          type: array
        commission:
          items:
            $ref: '#/components/schemas/Commission'
          type: array
        native_token:
          $ref: '#/components/schemas/NativeToken'
        novellia_version:
          description: Identifies the version of the specification in use.
          type: integer
        tags:
          description: Tags for sorting and filtering. "nsfw" indicates NSFW content
          items:
            type: string
          type: array
      required:
      - copyright
      - description
      - extension
      - id
      - image
      - name
      - native_token
      - novellia_version
      - publisher
      - resource
      - tags
      - version
      title: NovelliaStandardToken
      type: object
      x-examples: {}
    Extended721Token:
      description: Easily parsable data for Extended 721 Token
      example:
        image: image
        extension:
        - extension
        - extension
        name: name
        native_token:
          policy_id: policy_id
          asset_id: asset_id
        id: 5
      properties:
        native_token:
          $ref: '#/components/schemas/NativeToken'
        extension:
          description: List of extensions for parser to understand feature set. This
            may be empty, in which case the token is interpreted as just a 721 token.
          items:
            type: string
          type: array
        id:
          description: Token number in a set. Redundant field which makes no sense
            for tokens without a total-order.
          type: integer
        name:
          description: Display name for token.
          type: string
        image:
          description: Image URL without source redundancy.
          type: string
      required:
      - id
      - image
      - name
      title: Extended721Token
      type: object
    NativeToken:
      description: Definitions required to reference a native token
      example:
        policy_id: policy_id
        asset_id: asset_id
      properties:
        policy_id:
          description: On-chain policy-id
          type: string
        asset_id:
          description: On-chain asset-id
          type: string
      required:
      - asset_id
      - policy_id
      title: NativeToken
      type: object
    Attribution:
      description: Attribution information for artist, sculptor, whoever.
      example:
        author_name: author_name
        work_attributed: work_attributed
        url:
        - url
        - url
      properties:
        author_name:
          description: Name to give attribution to
          type: string
        url:
          description: URLs to portfolios, websites, etc.
          items:
            type: string
          type: array
        work_attributed:
          description: Description of work attributed
          type: string
      required:
      - author_name
      - url
      - work_attributed
      type: object
      x-examples:
        example-1:
          author_name: John Doe
          url:
          - https://www.artstation.com/
          - https://www.deviantart.com/
          work_attributed: Draculi Illustration
    NovelliaProduct:
      description: Product listed on Novelia without a token
      example:
        copyright: copyright
        resource:
        - content_type: content_type
          resource_id: resource_id
          description: description
          priority: 9
          url:
          - url
          - url
          multihash: multihash
          hash_source_type: hash_source_type
        - content_type: content_type
          resource_id: resource_id
          description: description
          priority: 9
          url:
          - url
          - url
          multihash: multihash
          hash_source_type: hash_source_type
        name: name
        publisher:
        - publisher
        - publisher
        description:
          short: short
          long: long
        commission:
        - address: address
          name: name
          percent: 3.616076749251911
        - address: address
          name: name
          percent: 3.616076749251911
        id: 7
        version: 4
        tags:
        - tags
        - tags
      properties:
        copyright:
          description: Attribution of rights to product.
          type: string
        publisher:
          description: List of publishers or entities involved in token creation.
            Useful for onlookers to determine token origin.
          items:
            type: string
          type: array
        version:
          description: Iteration in update sequence for product.
          type: integer
        name:
          description: Display name for token.
          type: string
        tags:
          description: Tags for sorting and filtering. "nsfw" indicates NSFW content
          items:
            type: string
          type: array
        commission:
          items:
            $ref: '#/components/schemas/Commission'
          type: array
        description:
          $ref: '#/components/schemas/DescriptionSet'
        resource:
          items:
            $ref: '#/components/schemas/OffChainResource'
          type: array
        id:
          description: Token number in a set. Redundant field which makes no sense
            for tokens without a total-order.
          type: integer
      required:
      - copyright
      - description
      - name
      - publisher
      - resource
      - tags
      - version
      title: NovelliaProduct
      type: object
    ProductsList:
      description: Light-weight list of products for further querying
      example:
        product_id:
        - product_id
        - product_id
      properties:
        product_id:
          description: List of available products
          items:
            type: string
          type: array
      required:
      - product_id
      title: ProductsList
      type: object
    Status_cardano:
      example:
        initialized: true
        sync_percentage: 0.8008281904610115
      properties:
        initialized:
          description: whether cardano-graphql is initialized
          type: boolean
        sync_percentage:
          description: cardano-graphql sync percentage, used to gauge when APIs will
            be available
          type: number
      required:
      - initialized
      - sync_percentage
      type: object
    Product_pricing:
      example:
        max_order_size: 6
        price_unit_amount: 0.8008281904610115
        price_currency_id: price_currency_id
      properties:
        price_currency_id:
          type: string
        price_unit_amount:
          type: number
        max_order_size:
          type: integer
      required:
      - max_order_size
      - price_currency_id
      - price_unit_amount
      type: object
    Product_organization:
      example:
        organization_id: organization_id
        name: name
        description: description
      properties:
        name:
          type: string
        organization_id:
          type: string
        description:
          description: Organization description. This can be markdown.
          type: string
      required:
      - description
      - name
      - organization_id
      type: object
    Product_market:
      example:
        name: name
        market_id: market_id
        description: description
      properties:
        name:
          type: string
        market_id:
          type: string
        description:
          description: Market description. This can be markdown.
          type: string
      required:
      - description
      - market_id
      - name
      type: object
    Product_stock:
      example:
        total_supply: 5.962133916683182
        available: 1.4658129805029452
      properties:
        available:
          type: number
        total_supply:
          type: number
      required:
      - available
      - total_supply
      type: object
    Product_metadata:
      example:
        date_listed: date_listed
        date_available: date_available
      properties:
        date_listed:
          type: string
        date_available:
          type: string
      required:
      - date_available
      - date_listed
      type: object
    Product_product:
      description: 'Immutable '
      example:
        novellia_standard_token:
          image: image
          copyright: copyright
          extension:
          - extension
          - extension
          resource:
          - content_type: content_type
            resource_id: resource_id
            description: description
            priority: 9
            url:
            - url
            - url
            multihash: multihash
            hash_source_type: hash_source_type
          - content_type: content_type
            resource_id: resource_id
            description: description
            priority: 9
            url:
            - url
            - url
            multihash: multihash
            hash_source_type: hash_source_type
          description:
            short: short
            long: long
          version: 2
          tags:
          - tags
          - tags
          name: name
          publisher:
          - publisher
          - publisher
          native_token:
            policy_id: policy_id
            asset_id: asset_id
          commission:
          - address: address
            name: name
            percent: 3.616076749251911
          - address: address
            name: name
            percent: 3.616076749251911
          id: 7
          novellia_version: 2
        product_id: product_id
        extended_721_token:
          image: image
          extension:
          - extension
          - extension
          name: name
          native_token:
            policy_id: policy_id
            asset_id: asset_id
          id: 5
        native_token:
          policy_id: policy_id
          asset_id: asset_id
        novellia_product:
          copyright: copyright
          resource:
          - content_type: content_type
            resource_id: resource_id
            description: description
            priority: 9
            url:
            - url
            - url
            multihash: multihash
            hash_source_type: hash_source_type
          - content_type: content_type
            resource_id: resource_id
            description: description
            priority: 9
            url:
            - url
            - url
            multihash: multihash
            hash_source_type: hash_source_type
          name: name
          publisher:
          - publisher
          - publisher
          description:
            short: short
            long: long
          commission:
          - address: address
            name: name
            percent: 3.616076749251911
          - address: address
            name: name
            percent: 3.616076749251911
          id: 7
          version: 4
          tags:
          - tags
          - tags
      properties:
        extended_721_token:
          $ref: '#/components/schemas/Extended721Token'
        novellia_standard_token:
          $ref: '#/components/schemas/NovelliaStandardToken'
        native_token:
          $ref: '#/components/schemas/NativeToken'
        novellia_product:
          $ref: '#/components/schemas/NovelliaProduct'
        product_id:
          description: Unique identifier of product
          type: string
      required:
      - product_id
      type: object
    Order_items:
      example:
        quantity: 0
        product_id: product_id
      properties:
        product_id:
          type: string
        quantity:
          type: integer
      required:
      - product_id
      - quantity
      type: object
    Order_customer:
      example:
        delivery_address: delivery_address
      properties:
        delivery_address:
          description: Address to deliver tokens to
          type: string
      required:
      - delivery_address
      type: object
    Order_payment:
      example:
        payment_address: payment_address
        payment_status: payment_status
        price_amount: 6.027456183070403
        price_currency_id: price_currency_id
      properties:
        payment_address:
          description: Address to deposit currency
          type: string
        price_currency_id:
          description: Policy ID of currency
          type: string
        price_amount:
          description: Amount due in currency. Use `number` for fiat, but ADA is lovelace
            integral
          type: number
        payment_status:
          description: Payment status (i.e. waiting, received, ...)
          type: string
      required:
      - payment_address
      - payment_status
      - price_amount
      - price_currency_id
      type: object
    OccultaNovelliaCharacter_card:
      description: Metadata relating to card / distribution
      properties:
        number:
          description: The character number
          type: integer
        release_set:
          description: The set this character was released in
          type: string
        rarity:
          description: Rarity of card ("Rare", "Kinda Not", "Not That Rare")
          type: string
      required:
      - number
      - rarity
      - release_set
      type: object
    OccultaNovelliaCharacter_progression:
      description: Character leveling progression between card variants
      properties:
        class:
          description: Character progression class
          type: string
        stage:
          description: Stage of character in class progression (1,2,3)
          type: integer
      required:
      - class
      - stage
      type: object
    OccultaNovelliaCharacter_stats:
      description: Integer stats
      properties:
        health:
          description: Damage sustained before dying
          type: integer
        attack:
          description: Multiplier for damage dealt as defined by attribute moves
          type: integer
        move:
          description: Action points cost per unit of movement
          type: integer
        slots:
          description: Slots used by character when added to a squad
          type: integer
      required:
      - attack
      - health
      - move
      - slots
      type: object
